<?php

declare(strict_types=1);

/*
 * FrankenPHP Worker Mode Entry Point for TYPO3
 *
 * This file is the entry point for FrankenPHP worker mode.
 * It is auto-generated by the ochorocho/frankenphp Composer installer.
 * DO NOT EDIT THIS FILE.
 */

ignore_user_abort(true);

// BOOT PHASE — runs once per worker process
$classLoader = require __DIR__ . '/../../../../../../vendor/autoload.php';
\TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run();
$container = \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader);

// REQUEST HANDLER — runs per incoming request
$handler = static function () use ($container): void {
    // Re-establish output buffering — AbstractApplication::sendResponse() may clear
    // all output buffers when handling SelfEmittableStreamInterface responses (file downloads).
    // Without this, subsequent requests would have no output buffering.
    ob_start();

    if ($container->has(\TYPO3\CMS\Core\Http\Application::class)) {
        $container->get(\TYPO3\CMS\Core\Http\Application::class)->run();
        return;
    }
    // Fallback to install tool
    $container->get(\TYPO3\CMS\Install\Http\Application::class)->run();
};

// WORKER LOOP
$maxRequests = (int)($_SERVER['MAX_REQUESTS'] ?? 0);
for ($nbRequests = 0; !$maxRequests || $nbRequests < $maxRequests; ++$nbRequests) {
    $keepRunning = \frankenphp_handle_request($handler);
    gc_collect_cycles();
    if (!$keepRunning) {
        break;
    }
}
